<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Podoquiro.Ponto</RootNamespace>
    <AssemblyName>SourceAfisMatcher</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SourceAFIS" Version="3.14.0" />
  </ItemGroup>
</Project>
